server:
  port: 8030
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30

# spring
spring:
  profiles:
    include: service-test

# ignored-urls
ignored:
  urls:
    - /login/expired
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/v2/api-docs

#logging:
#  level:
#    root: debug

